name = "Xiao"
license = "MIT"
licenselink = "https://github.com/ghostsf/hugo-theme-xiao/blob/master/LICENSE.md"
description = "A minimalistic and responsive theme from my code blog named xiao."
homepage = "http://code.ghostsf.com"
tags = ["blog", "beautiful", "disqus", "rss", "syntax highlighting", "tags"]
features = ["blog", "beautiful", "disqus", "rss", "syntax highlighting", "tags"]
min_version = 0.20

[author]
  name = "ghostsf"
  homepage = "http://ghostsf.com"

[[original]]
  name = "Xiao"
  homepage = "http://code.ghostsf.com"
  repo = "https://github.com/ghostsf/hugo-theme-xiao"
